language: node_js
node_js:
  - "0.12"
  - "0.10"
before_install:
  -npm install -g grunt-cli
notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
cache:
  directories:
    - node_modules
