language: node_js
node_js:
  - 'node'
before_install:
  - npm install -g grunt-cli
  - cp src/js/ga.secret.js src/js/ga.js
notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
cache:
  directories:
    - node_modules
