language: node_js
node_js:
  - "0.12"
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - cp src/js/ga.secret.js src/js/ga.js
  - cp src/js/maptiks.secret.js src/js/maptiks.js
notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
cache:
  directories:
    - node_modules
